# Minimum amount of players
min_players: 2

# Maximum amount of players
max_players: 12

# Time before start
time_before_start: 30

# Spawn points for the 1st map
spawn_points:
  - 53.5 110 5.5 90 0
  - 33.5 111 28.5 126 8
  - 18.5 112 43.5 146 6
  - -5.5 110 63.5 -180 6
  - -28.5 111 43.5 -148 3
  - -43.5 112 27.5 -123 3
  - -63.5 110 4.5 -90 0
  - -43.5 111 -19.5 -60 0
  - -28.5 112 -35.5 -30 0
  - -5.5 110 -55.5 0 0
  - 18.5 111 -35.5 30 0
  - 33.5 112 -18.5 60 0